version: '3.8'

services:
  reservations:
    image: node:22-alpine
    container_name: reservations
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '50054:50051'
    command: sh -c "npx nest start reservations --watch"
    env_file:
      - .env
    stdin_open: true
    tty: true
  facilities:
    image: node:22-alpine
    container_name: facilities
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '50053:50051'
    command: sh -c "npx nest start facilities --watch"
    env_file:
      - .env
    stdin_open: true
    tty: true
  users:
    image: node:22-alpine
    container_name: users
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '50052:50051'
    command: sh -c "npx nest start users --watch"
    env_file:
      - .env
    stdin_open: true
    tty: true
  gateway:
    image: node:22-alpine
    container_name: gateway
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:80'
    command: sh -c "npx nest start gateway --watch"
    env_file:
      - .env
    stdin_open: true
    tty: true
networks:
  default:
    name: supabase_network_play-spot-services
    external: true
